#cs ----------------------------------------------------------------------------

 AutoIt Version: 3.2+
 Author:         Edmundo Fasano (Ed_Maximized) edmundofasano@gmail.com

 Script Function:
    Convert a text file in a string and generate autoit code
    
    Usefull to include long txt files into programs

#ce ----------------------------------------------------------------------------

Dim $Text=''
$TxtFile=FileOpenDialog('Select a TXT file',@ScriptDir,'All txt files (*.*)')
$File = FileOpen($TxtFile, 0)

#Region --- CodeWizard generated code Start ---
;InputBox features: Title=Yes, Prompt=Yes, Default Text=Yes
If Not IsDeclared("sInputBoxAnswer") Then Dim $sInputBoxAnswer
$sInputBoxAnswer = InputBox("Txt2au3","Input a variable name without leading '$'","a"," ","-1","-1","-1","-1")
Select
   Case @Error = 0 ;OK - The string returned is valid
        $var='$'&$sInputBoxAnswer
   Case @Error = 1 ;The Cancel button was pushed
       Exit
   Case @Error = 3 ;The InputBox failed to open
       Exit
EndSelect
#EndRegion --- CodeWizard generated code End ---



$Main = GUICreate('Txt2Au3 - '&$TxtFile, 500, 380)
$Edit = GUICtrlCreateEdit('', 0, 0, 500, 380)
GUISetState()

$Text="#region ;generated by Txt2au3 - code by Ed_maximized"&@CRLF&$var&'=""'&@CRLF

; Check if file opened for reading OK
If $File = -1 Then
    MsgBox(0, "Error", "Unable to open file.")
    Exit
EndIf
; Read in lines of text until the EOF is reached
While 1
    $Line = FileReadLine($File)
    If @error = -1 Then ExitLoop
    $Line = _ReplaceSingleQuotes($Line)
    $Text &= $var&' &="' & $Line&'"&@CRLF'&@CRLF
    ConsoleWrite($line)
Wend
FileClose($File)
$Text &= 'MsgBox(0,"Test MsgBox",'&$var&') ;test line you can comment this'&@CRLF
$Text &= '#endregion'

GUICtrlSetData($Edit,$Text)

While 1
    Switch GUIGetMsg()
        Case - 3
            Exit
    EndSwitch
WEnd

Func _ReplaceSingleQuotes($Line)
    Dim $i,$j,$k=""
    For $i=1 To StringLen($line)
        Switch StringMid($line,$i,1)
            Case Chr(34)
                $k &= Chr(34)&Chr(34)
            Case Else
                $k &= StringMid($line,$i,1)
        EndSwitch
    Next
    Return $k
EndFunc
