#NoTrayIcon
$txtfile = RegRead("HKCR\txtfile\shell\open\command", "")
$inifile = RegRead("HKCR\inifile\shell\open\command", "")

If Not ProcessExists("wbload.exe") Then
	$nameThemes = 'SilverAS'
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "CanUpgrade", "REG_SZ", '1')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Path", "REG_SZ", @ScriptDir)
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "EXE", "REG_SZ", 'wbconfig.exe')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Version", "REG_SZ", '4.60')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Revision", "REG_SZ", '460')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "NeedsReboot", "REG_SZ", '1')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Startup", "REG_SZ", '1')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Disable", "REG_SZ", 'wbload.exe UNLOAD')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Updated", "REG_SZ", '12/10/2005 20:47:44')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Tooltip", "REG_SZ", 'WB 4.60')
	RegWrite("HKLM\SOFTWARE\Stardock\ObjectDesktop\WindowBlinds", "Type", "REG_SZ", 'enhanced')
	RegWrite("HKLM\SOFTWARE\Stardock\WindowBlinds\WB5.ini\INSTALLED", "RealPath", "REG_SZ", @ScriptDir)
	RegWrite("HKLM\SOFTWARE\Stardock\WindowBlinds\WB5.ini\INSTALLED", "Path", "REG_SZ", 'Object Desktop')
	RegWrite("HKLM\SOFTWARE\Stardock\WindowBlinds\WB5.ini\INSTALLED", "Path2", "REG_SZ", 'WB-g1de774')
	RegWrite("HKLM\SOFTWARE\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "INET", "REG_SZ", 'O')
	RegWrite("HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WindowBlinds", "InstallLocation", "REG_SZ", @ScriptDir)
	RegWrite("HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WindowBlinds", "Publisher", "REG_SZ", 'Stardock.net, Inc.')
	RegWrite("HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WindowBlinds", "VersionMajor", "REG_SZ", '3')
	RegWrite("HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WindowBlinds", "VersionMinor", "REG_SZ", '460')
	RegWrite("HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\Notify\WB", "Asynchronous", "REG_DWORD", '0')
	RegWrite("HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\Notify\WB", "DllName", "REG_SZ", @ScriptDir & '\fastload.dll')
	RegWrite("HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\Notify\WB", "Logon", "REG_SZ", 'StartWB')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\0", "COL", "REG_SZ", '65280')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\1", "COL", "REG_SZ", '15326093')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\10", "COL", "REG_SZ", '8453888')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\11", "COL", "REG_SZ", '8421440')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\2", "COL", "REG_SZ", '9982701')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\3", "COL", "REG_SZ", '4975603')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\4", "COL", "REG_SZ", '4227072')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\5", "COL", "REG_SZ", '8404992')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\6", "COL", "REG_SZ", '4227327')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\7", "COL", "REG_SZ", '128')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\8", "COL", "REG_SZ", '16777088')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\9", "COL", "REG_SZ", '8388863')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\global", "noStatus", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\global", "noMenu", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\MAP", "Red", "REG_SZ", '141')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\MAP", "Green", "REG_SZ", '219')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\MAP", "Blue", "REG_SZ", '233')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\MAP", "LCOL", "REG_SZ", '4')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\MAP", "FORCE2", "REG_SZ", '255')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\wb.ini\MAP2", "Enabled", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\Installed", "Path", "REG_SZ", @ScriptDir)
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\map", "HueAdjust", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Skinset", "REG_SZ", @ScriptDir & '\' & $nameThemes & '\' & $nameThemes & '.uis')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Skinset2", "REG_SZ", $nameThemes)
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "DoMenuBorders", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "UseChecks", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "UseButtons", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "UseColours", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "TaskBar", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "bitBmp", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "OptionNum", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "ShowConfig", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "AllowCol", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "noDiaBitmaps", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "transTxt", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "SubSkin", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "TOOLON", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "noExpBitmaps", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "stretchBitmaps", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "noFlatTool", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Wallpaper", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Icons", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "SysTray", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "UnloadWarn", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Prompt", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Fade", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Over2", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "UserMode", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "SORTMODE", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "DoExplorerColour", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "FastExplorer", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "ExpTrans", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "INSTANTON", "REG_SZ", '1')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "OverrideXP", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "InclusionList", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "OverrideShell", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "LastLoc", "REG_SZ", 'X:\')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WB5.ini\WBLiteFX", "Lastsub", "REG_SZ", '0')
	RegWrite("HKCU\Software\Stardock\WindowBlinds\WindowFX.ini\WindowFX", "Lang", "REG_SZ", 'Russian')
	_Run()
	Exit
EndIf
GUICreate("Выбор темы", 265, 125)
GUISetIcon(@ScriptDir & '\wbload.exe')
$Silver = GUICtrlCreateButton("Silver", 5, 5, 55, 22)
GUICtrlSetTip(-1, "Применить тему Silver" & @CRLF & "с указанным шрифтом и размером шрифта")
$fontf1 = GUICtrlCreateCombo("", 70, 5, 130, 22)
GUICtrlSetData(-1, 'Смешанный|Tahoma|Arial|Verdana|Microsoft Sans Serif', 'Arial')
GUICtrlSetTip($fontf1, 'Выбираем шрифт')
$fontHeight1 = GUICtrlCreateCombo("", 210, 5, 45, 22)
GUICtrlSetData(-1, '11|12|13|14|15|16|17', '14')
GUICtrlSetTip($fontHeight1, 'Выбираем размер шрифта')
$black = GUICtrlCreateButton("black", 5, 35, 55, 22)
GUICtrlSetTip(-1, "Применить тему black" & @CRLF & "с указанным шрифтом и размером шрифта")
$fontf2 = GUICtrlCreateCombo("", 70, 35, 130, 22)
GUICtrlSetData(-1, 'Tahoma|Arial|Verdana|Microsoft Sans Serif', 'Arial')
GUICtrlSetTip($fontf2, 'Выбираем шрифт')
$fontHeight2 = GUICtrlCreateCombo("", 210, 35, 45, 22)
GUICtrlSetData(-1, '11|12|13|14|15|16|17', '14')
GUICtrlSetTip($fontHeight2, 'Выбираем размер шрифта')
$Other = GUICtrlCreateButton("Другое", 5, 65, 55, 22)
GUICtrlSetTip(-1, "Применить указанную тему" & @CRLF & "(имя каталога)")
$Otherinput = GUICtrlCreateInput('введите имя темы', 70, 65, 137, 22)
$unwb = GUICtrlCreateButton("Выгрузить WB", 5, 95, 96, 22)
GUICtrlSetTip(-1, "Выгрузить WindowBlinds")
$stwb = GUICtrlCreateButton("Старт WB", 111, 95, 96, 22)
GUICtrlSetTip(-1, "Старт WindowBlinds")
GUISetState()
While 1
	Switch GUIGetMsg()
		Case $Silver
			$fontf_v = GUICtrlRead($fontf1)
			$fontf = $fontf_v
			If $fontf_v = "Смешанный" Then $fontf = "Verdana"
			$fontHeight = GUICtrlRead($fontHeight1)
			$ini = @ScriptDir & '\SilverAS\SilverAS.uis'
			IniWrite($ini, "SystemFont0", "FontHeight", '-' & $fontHeight +1)
			IniWrite($ini, "SystemFont1", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "SystemFont2", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "SystemFont3", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "SystemFont4", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "SystemFont5", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "Font0", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "Font1", "FontHeight", '-' & $fontHeight + 9)
			IniWrite($ini, "Font2", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "Font3", "FontHeight", '-' & $fontHeight +6)
			IniWrite($ini, "Font4", "FontHeight", '-' & $fontHeight - 3)
			IniWrite($ini, "Font6", "FontHeight", '-' & $fontHeight - 2)
			IniWrite($ini, "SystemFont1", "FontName", $fontf)
			IniWrite($ini, "SystemFont3", "FontName", $fontf)
			IniWrite($ini, "SystemFont4", "FontName", $fontf)
			IniWrite($ini, "SystemFont5", "FontName", $fontf)
			IniWrite($ini, "Font1", "FontName", $fontf)
			IniWrite($ini, "Font2", "FontName", $fontf)
			IniWrite($ini, "Font3", "FontName", $fontf)
			IniWrite($ini, "Font4", "FontName", $fontf)
			IniWrite($ini, "Font6", "FontName", $fontf)
			If $fontf_v = "Смешанный" Then $fontf = "Arial"
			IniWrite($ini, "SystemFont0", "FontName", $fontf)
			IniWrite($ini, "SystemFont2", "FontName", $fontf)
			IniWrite($ini, "Font0", "FontName", $fontf)
			_Run(' SilverAS\SilverAS.uis')
			Sleep(300)
			_Set()
		Case $black
			$fontf = GUICtrlRead($fontf2)
			$fontHeight = GUICtrlRead($fontHeight2)
			$ini = @ScriptDir & '\black\black.uis'
			For $i = 0 To 5
				IniWrite($ini, "SystemFont" & $i, "FontHeight", '-' & $fontHeight)
				IniWrite($ini, "Font" & $i, "FontHeight", '-' & $fontHeight)
				IniWrite($ini, "SystemFont" & $i, "FontName", $fontf)
				IniWrite($ini, "Font" & $i, "FontName", $fontf)
			Next
			IniWrite($ini, "Font6", "FontHeight", '-' & $fontHeight)
			IniWrite($ini, "Font6", "FontName", $fontf)
			_Run(' black\black.uis')
			Sleep(300)
			_Set()
		Case $Other
			$tmp = GUICtrlRead($Otherinput)
			_Run(' ' & $tmp & '\' & $tmp & '.uis')
			_Set()
		Case $unwb
			_Run(' UNLOAD')
		Case $stwb
			_Run()
		Case -3
			$tmp = RegRead("HKCR\txtfile\shell\open\command", "")
			If $txtfile<>$tmp Then RegWrite("HKCR\txtfile\shell\open\command","","REG_SZ", $txtfile)
			$tmp = RegRead("HKCR\inifile\shell\open\command", "")
			If $inifile<>$tmp Then RegWrite("HKCR\inifile\shell\open\command","","REG_SZ", $inifile)
			Exit
	EndSwitch
WEnd

Func _Run($arg = '')
	Run(@ScriptDir & '\wbload.exe' & $arg, '', @SW_HIDE)
EndFunc

Func _Set()
	Local $hWnd = WinWait("[CLASS:tooltips_class32]", "", 2) ; окон много но последнее является первым в списке Z-порядка
	; если дескриптор существует, его окно видимо и текст заголовка содержит указанную строку, то
	If $hWnd And BitAND(WinGetState($hWnd), 2) And _
	StringInStr(WinGetTitle($hWnd), 'Нажмите эту подсказку для применения скина, либо сделайте это на вкладке "Оформление" в свойствах экрана') Then
		Local $aPos = WinGetPos($hWnd)
		Local $aMousePos = MouseGetPos() ; чтобы возвратить курсор
		Sleep(60)
		MouseClick("primary", $aPos[0]+$aPos[2]/2, $aPos[1]+$aPos[3]/2, 1, 0) ; клик на подсказке в трее
		MouseMove($aMousePos[0], $aMousePos[1], 0)
	Else
		Return MsgBox(4096, 'Сообщение', 'Не найдена всплывающая подсказка в трее')
	EndIf
EndFunc