#NoTrayIcon
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","fcalloc.dll","REG_SZ",@ScriptDir&'\fcalloc.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","fnls.dll","REG_SZ",@ScriptDir&'\fnls.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","fobject.dll","REG_SZ",@ScriptDir&'\fobject.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","ftrace.dll","REG_SZ",@ScriptDir&'\ftrace.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","icu34.dll","REG_SZ",@ScriptDir&'\icu34.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","rpc_client.dll","REG_SZ",@ScriptDir&'\rpc_client.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","resource.dll","REG_SZ",@ScriptDir&'\resource.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","gc.dll","REG_SZ",@ScriptDir&'\gc.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","sequence_parser.dll","REG_SZ",@ScriptDir&'\sequence_parser.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","thread_pool.dll","REG_SZ",@ScriptDir&'\thread_pool.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","ntmsapia.dll","REG_SZ",@ScriptDir&'\ntmsapia.dll')
RegWrite("HKLM\SOFTWARE\Acronis\CommonComponents","libcrypto9.dll","REG_SZ",@ScriptDir&'\libcrypto9.dll')
RegWrite("HKLM\SOFTWARE\Acronis\DDDeployer","ExePath","REG_SZ",@ScriptDir&'\DDDeployer.exe')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\CommonComponents","fcalloc.dll","REG_SZ",@ScriptDir&'\fcalloc.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\CommonComponents","fobject.dll","REG_SZ",@ScriptDir&'\fobject.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\CommonComponents","icu34.dll","REG_SZ",@ScriptDir&'\icu34.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\CommonComponents","fnls.dll","REG_SZ",@ScriptDir&'\fnls.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\CommonComponents","gc.dll","REG_SZ",@ScriptDir&'\gc.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\CommonComponents","thread_pool.dll","REG_SZ",@ScriptDir&'\thread_pool.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\CommonComponents","resource.dll","REG_SZ",@ScriptDir&'\resource.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\Backup","Family","REG_SZ",'Backup')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\Backup","Id","REG_DWORD",'945607834')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\Backup","Path","REG_SZ",@ScriptDir&'\Backup.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\Backup","Version","REG_SZ",'1.0.19.110')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupFilePlace","BasePath","REG_SZ",'file')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupFilePlace","Id","REG_DWORD",'843337818')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupFilePlace","IsBackupPlace","REG_SZ",'1')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupFilePlace","Path","REG_SZ",@ScriptDir&'\BackupFilePlace.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupFilePlace","SupportedSchemes","REG_SZ",'file:1')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupFilePlace","Version","REG_SZ",'1.0.19.108')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupNetworkPlace","BasePath","REG_SZ",'network')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupNetworkPlace","Id","REG_DWORD",'-2076516075')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupNetworkPlace","IsBackupPlace","REG_SZ",'1')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupNetworkPlace","Path","REG_SZ",@ScriptDir&'\BackupNetworkPlace.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupNetworkPlace","SupportedSchemes","REG_SZ",'file')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\BackupNetworkPlace","Version","REG_SZ",'1.0.19.107')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskBackup","Archiver","REG_SZ",'1')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskBackup","Family","REG_SZ",'Backup')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskBackup","Id","REG_DWORD",'-1494547706')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskBackup","Path","REG_SZ",@ScriptDir&'\DiskBackup.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskBackup","Version","REG_SZ",'1.0.19.107')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskManager","Id","REG_DWORD",'-859933539')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskManager","Path","REG_SZ",@ScriptDir&'\DiskManager.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\DiskManager","Version","REG_SZ",'1.0.19.348')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\FileBackup","Archiver","REG_SZ",'1')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\FileBackup","Family","REG_SZ",'Backup')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\FileBackup","Id","REG_DWORD",'1471843297')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\FileBackup","Path","REG_SZ",@ScriptDir&'\FileBackup.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\FileBackup","Version","REG_SZ",'1.0.19.104')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\PlaceBrowser","Family","REG_SZ",'Backup')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\PlaceBrowser","Id","REG_DWORD",'1449266612')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\PlaceBrowser","Path","REG_SZ",@ScriptDir&'\PlaceBrowser.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\PlaceBrowser","Version","REG_SZ",'1.0.19.107')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\URI","Id","REG_DWORD",'314307499')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\URI","Path","REG_SZ",@ScriptDir&'\URI.dll')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEcho\Fomatik\Plugins\URI","Version","REG_SZ",'1.0.19.317')
RegWrite("HKLM\SOFTWARE\Acronis\TrueImageEnterprise\Settings","WorkingDir","REG_SZ",@ScriptDir&'')
RegWrite("HKLM\SOFTWARE\Acronis\UniversalRestore","enterprise","REG_SZ",' 24103 96 22103120 17102109108  7120 12 20  3 23 30120 18108103 96 99120  3  5 20 17 19')
RegWrite("HKLM\SOFTWARE\Classes\*\shellex\ContextMenuHandlers\{C539A15A-3AF9-4c92-B771-50CB78F5C751}","","REG_SZ",'')
RegWrite("HKLM\SOFTWARE\Classes\.tib","","REG_SZ",'tibfile')
RegWrite("HKLM\SOFTWARE\Classes\AppID\{C4E69DB9-E094-483e-B922-E7ADE65FB497}","","REG_SZ",'Acronis True Image Shell Extension Backend')
RegWrite("HKLM\SOFTWARE\Classes\AppID\{C4E69DB9-E094-483e-B922-E7ADE65FB497}","DllSurrogate","REG_SZ",'')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15A-3AF9-4c92-B771-50CB78F5C751}","","REG_SZ",'Acronis True Image Shell Context Menu Extension')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15A-3AF9-4c92-B771-50CB78F5C751}\InProcServer32","","REG_SZ",@ScriptDir&'\tishell.dll')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15A-3AF9-4c92-B771-50CB78F5C751}\InProcServer32","ThreadingModel","REG_SZ",'Apartment')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15B-3AF9-4c92-B771-50CB78F5C751}","","REG_SZ",'Acronis True Image Shell Extension')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15B-3AF9-4c92-B771-50CB78F5C751}\Implemented Categories\{00021490-0000-0000-C000-000000000046}","","REG_SZ",'')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15B-3AF9-4c92-B771-50CB78F5C751}\InProcServer32","","REG_SZ",@ScriptDir&'\tishell.dll')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15B-3AF9-4c92-B771-50CB78F5C751}\InProcServer32","ThreadingModel","REG_SZ",'Apartment')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15B-3AF9-4c92-B771-50CB78F5C751}\ShellFolder","Attributes","REG_DWORD",'-1610612736')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15C-3AF9-4c92-B771-50CB78F5C751}","","REG_SZ",'Acronis True Image Shell Extension Backend')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15C-3AF9-4c92-B771-50CB78F5C751}","AppID","REG_SZ",'{C4E69DB9-E094-483e-B922-E7ADE65FB497}')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15C-3AF9-4c92-B771-50CB78F5C751}\InProcServer32","","REG_SZ",@ScriptDir&'\tishell32.dll')
RegWrite("HKLM\SOFTWARE\Classes\CLSID\{C539A15C-3AF9-4c92-B771-50CB78F5C751}\InProcServer32","ThreadingModel","REG_SZ",'Apartment')
RegWrite("HKLM\SOFTWARE\Classes\Drive\shellex\ContextMenuHandlers\{C539A15A-3AF9-4c92-B771-50CB78F5C751}","","REG_SZ",'')
RegWrite("HKLM\SOFTWARE\Classes\Folder\shellex\ContextMenuHandlers\{C539A15A-3AF9-4c92-B771-50CB78F5C751}","","REG_SZ",'')
RegWrite("HKLM\SOFTWARE\Classes\tibfile","","REG_SZ",'Acronis True Image Backup Archive')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\CLSID","","REG_SZ",'{C539A15B-3AF9-4c92-B771-50CB78F5C751}')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\DefaultIcon","","REG_SZ",@ScriptDir&'\tishell.dll,0')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\Shell\open","","REG_SZ",'')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\Shell\open\command","","REG_SZ",'explorer /idlist,%I,%L')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\Shell\open\ddeexec","","REG_SZ",'[ViewFolder("%l", %I, %S)]')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\Shell\open\ddeexec","NoActivateHandler","REG_SZ",'')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\Shell\open\ddeexec\application","","REG_SZ",'Folders')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\Shell\open\ddeexec\ifexec","","REG_SZ",'[]')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\Shell\open\ddeexec\topic","","REG_SZ",'AppProperties')
RegWrite("HKLM\SOFTWARE\Classes\tibfile\ShellEx\ContextMenuHandlers\{C539A15A-3AF9-4c92-B771-50CB78F5C751}","","REG_SZ",'')

Run(@ScriptDir&'\trueimage.exe')